### ISSUE TITLE
connection uri doesn't support unicode in python 2.x

### ISSUE THREAD

**Issue by ygl-rg** [twisted/txmongo#127]
Hi 

   I notice uri type assertion in class Connection Pool.__init__ has been changed from 
  assert isinstance(uri, basestring) to assert isinstantce(uri, str) like following:

ConnectionPool(object):
    def __init__(self, uri="mongodb://127.0.0.1:27017", pool_size=1, ssl_context_factory=None, **kwargs):
        assert isinstance(uri, str)

 when I use an unicode string, The Connection pool init will fail. 

   Is it possible to use basestring back?

Regards

gelin yan

**Comment by psi29a** [comment]
Looks like this one fell through the cracks, no check with unicode in the tests.

We'll not revert it back to basestring because it doesn't exist in Python3. We will look into using Twisted's compat library to solve this. 
https://github.com/twisted/twisted/blob/trunk/twisted/python/compat.py

Thanks for pointing this out!

**Comment by psi29a** [comment]
Should be fixed here: 
https://github.com/twisted/txmongo/commit/fdfec716f5830318cf1c8e3310dea5ededf20ef6

**Comment by ygl-rg** [comment]
thx. I have tested 15.2.2 and this problem is gone.
