### ISSUE TITLE
insert_many with BulkWriteError

### ISSUE THREAD

**Issue by jhonny111s** [twisted/txmongo#145]
When use insert_may with ordered=False I expected have in BulkWriteError whith all duplicated keys but only return the last, how can i get all error (knowing data that induce error)

**Comment by IlyaSkriblovsky** [comment]
Yes, I've checked this and it looks like txmongo raises invalid exceptions for `insert_many` and possibly other `*_many` methods (`DuplicateKeyError` instead of `BulkWriteError`).

We call `pymongo.helpers._check_write_command_response` that unwraps Mongo's error response into single `DuplicateKeyError`. This is correct for `*_one` methods, but not for `*_many`.

**Comment by IlyaSkriblovsky** [comment]
Fixed this in #146. Could you please check if that branch raises expected exception type for you?

**Comment by jhonny111s** [comment]
I use pip install txmongo but this install older master, how can install this branch. thanks

**Comment by IlyaSkriblovsky** [comment]
Please try `pip install https://github.com/IlyaSkriblovsky/txmongo/archive/insert-many-bulk-errors.zip`

**Comment by jhonny111s** [comment]
@IlyaSkriblovsky  thanks so much, works fine for me

**Comment by IlyaSkriblovsky** [comment]
@jhonny111s This patch was merged into master, so you can use `pip install https://github.com/twisted/txmongo/archive/master.zip` until new release of txmongo will be published to PyPI
