### ISSUE TITLE
Txmongo is unable to handle more than 1000 objects in bulk operations

### ISSUE THREAD

**Issue by jsandovalc** [twisted/txmongo#149]
Hi. I'm testing the following code using txmongo 16.1.0. Basically, I'm sending 1001 objects to an insert_many.  It's raising pymongo.errors.OperationFailure: TxMongo: command SON ... ('writeConcern', {})]) on namespace foo.$cmd failed with 'exceeded maximum write batch size of 1000'
``` python
import time
import txmongo
from twisted.internet import defer, reactor


@defer.inlineCallbacks
def example():
    mongo = yield txmongo.connection.ConnectionPool('mongodb://127.0.0.1:27018')

    foo = mongo.foo  # `foo` database
    test = foo.test  # `test` collection

    # insert some data
    insert_data = []
    for x in range(1001):
        insert_data.append({"something": x*time.time()})

    result = yield test.insert_many(insert_data)

if __name__ == '__main__':
    example().addCallback(lambda ign: reactor.stop())
    reactor.run()
```
Mongo has a limit of 1000 for Bulk operations, but drivers usually handle this by dividing batch operations. Pymongo does not fail with many more objects.

**Comment by IlyaSkriblovsky** [comment]
You are right, PyMongo does chunking of inserted documents by 16Mb or 1000 pcs as part of their Bulk operations support. TxMongo doesn't have distinct Bulk API and our `insert_many` is rather simple. Patches are welcome :)

**Comment by jsandovalc** [comment]
I see. Any suggestions to implement this feature?. I mean, I checked pymongo and they have a Buik API (a bulk module). Would it be necessary to implement something similar in txmongo and use it in insert_many?. Or a simpler solution could be used?.

**Comment by IlyaSkriblovsky** [comment]
I don't think the full-weight Bulk API is needed. We could just modify `insert_many` because it is the only command for now that may send arbitrary amount of data to DB. We can modify it to split documents in batches when reaching 16Mb or 1000pcs limit. But it needs to carefully handle all combinations of ordered/unordered and acknowledged/unacknowledged write-concern.

Is it an urgent issue for you? If not, I can try to solve this on the weekend.

**Comment by jsandovalc** [comment]
Ah, many thanks. It's not that urgent. I think I can wait a couple of weeks, but, if I was going to do it I needed to start as soon as I could, because I don't know that much about txmongo.

**Comment by IlyaSkriblovsky** [comment]
It may be easier to me since I'm familiar with the sources. But I'm not sure I will be able to start untill weekend. But if you want to fix it yourself, please let me know for us to not do the same work twice.

**Comment by jsandovalc** [comment]
I'll wait. Thanks.

**Comment by IlyaSkriblovsky** [comment]
I've implemented splitting documents in batches here: https://github.com/IlyaSkriblovsky/txmongo/tree/insert-many-1k

I hadn't wrote tests yet, so it is not ready for Pull Request. But I would appreciate if you try it and check that it works correctly now (with both >1000pcs and >16Mb).

It turned out to be trickier than I thought because BSON serialization is costly and good implementation should do it only once. So, I did it the same way as PyMongo does: manually composing BSON at the same time as checking batch boundaries. Otherwise two serializations would be needed: one while splitting batches and another while sending command.

There is also complex logic that handles all [ack, unack]×[ordered, unordered] cases. All four cases should be carefully tested.

**Comment by jsandovalc** [comment]
Awesome. I'll try to test it as soon as possible and I'll write what I find out.

**Comment by IlyaSkriblovsky** [comment]
I've just fixed a couple of silly bugs. Please be sure to test latest version.

Unittests also added, now waiting for Travis' verdict and will create PR if it is ok.

**Comment by jsandovalc** [comment]
Hi. I just did some tests with different configurations and amount of documents and the branch seems to be working fine.

I also tested it with the code of my app in a test environment and it worked pretty well. Amazing work, many thanks.

**Comment by psi29a** [comment]
Thank you for testing this! :)

**Comment by IlyaSkriblovsky** [comment]
Thanks!
