### ISSUE TITLE
Getmore in find loop may not be correct

### ISSUE THREAD

**Issue by trenton42** [twisted/txmongo#182]
I have been using queries with cursors recently, and just noticed that the cursor always returns two chunks of data if there are more than 100 documents in the query. I was a little puzzled when I had a 10,000 document find that returned the first 101, then the remaining 9,899 documents.

After digging in, I realized that the find method uses the `send_GETMORE` method to explicitly request the rest of the documents with the `n_to_return` argument. I suspect (though I couldn't find any conclusive evidence) that this isn't the best behavior. I can create a patch to change this, but I wanted to get some feedback before making any changes.

**Comment by IlyaSkriblovsky** [comment]
This is an expected behavior of MongoDB. If you don't explicitly set `limit`, txmongo will send `None` for `n_to_return` and MongoDB will return up to 101 docs in the first batch and up to 16Mb in each following. This is documented here: https://docs.mongodb.com/manual/tutorial/iterate-a-cursor/#cursor-batches (in Tutorials somewhy).

We are using `n_to_return` only to specify maximum number of documents we want to get and only if `limit` is specified. This is not the same as `batchSize`.

**Comment by IlyaSkriblovsky** [comment]
@trenton42 This is an expected behavior of MongoDB. If you don't explicitly set limit, txmongo will send None for n_to_return and MongoDB will return up to 101 docs in the first batch and up to 16Mb in each following. This is documented here: https://docs.mongodb.com/manual/tutorial/iterate-a-cursor/#cursor-batches (in Tutorials somewhy).

We are using n_to_return only to specify maximum number of documents we want to get and only if limit is specified. This is not the same as batchSize.

**Comment by trenton42** [comment]
Thanks @IlyaSkriblovsky! I did notice that if I remove the `n_to_return` parameter, it returned batches of ~100 each, so I'm not sure if the default behavior has changed on Mongo's end. I am good with closing this issue if this behavior is expected.

**Comment by IlyaSkriblovsky** [comment]
I didn't tested this, but it sounds like not specifying `n_to_return` in GETMORE makes it to behave like initial QUERY response -- return `min(101pcs, 1Mb)` of documents. But QUERY seems to always return `min(101pcs, 1Mb)` of data, regardless of what we specify in `n_to_return`.

This is suboptimal if you are expecting to get thousands of docs from DB, but this is how MongoDB behaves when you don't specify `batchSize`. This is probably a kind of trade-off between initial response time and bulk performance. The proper way to get maximum performance when fetching large datasets is to specify `batchSize` to large number. But unfortunately, txmongo doesn't (yet) support this.
