### ISSUE TITLE
Support passing additional options to getLastError

### ISSUE THREAD

**Issue by nkvoll** [twisted/txmongo#24]
getLastError supports multiple options (see http://www.mongodb.org/display/DOCS/getLastError+Command#getLastErrorCommand-Options), but providing these options are currently not possible in txmongo.

This is supported by pymongo by passing extra keyword arguments to the insert/update/remove commands. Default options are possible to set on both the database and collection instances. It would be great having this feature here.

**Comment by IlyaSkriblovsky** [comment]
Since 15.1.0 release TxMongo supports Write-Concern options:

- For old-style query methods write-concern options can be passed as named args: `coll.insert(..., w=1, j=True)`. Specified write-concern options will be passed to `getLastError`.
- For new-style query methods (`*_one`, `*_many`) write-concern options can be set using `Collection.with_options` method: `coll.with_options(write_concern=WriteConcern(w=2, j=True)).insert_one(...)`. Write-concern options will be passed to corresponding MongoDB query command.

So this issue is't relevant anymore
